fix cstyle issue in ./src/istgt_lu.h
openebs/istgt pull request #105
Opened 2018-10-06 10:11 UTC by cbanupama

2018-10-06 10:45 UTC, utkarshmani1997 commented
@cbanupama it will be good if you provide the output of the `./cstyle.pl filename`.

2018-10-07 17:40 UTC, vishnuitta commented on src/istgt_lu.h
> +typedef enum
these changes are not required as cstyle is not showing any error here, and, in the code, 'flower braces' should be given in the same line of 'enum', 'struct', 'if', 'for' etc.

2018-10-07 17:40 UTC, vishnuitta requested changes
As mentioned in other PRs, request you to re-do the PR

2020-04-07 06:20 UTC, mittachaitu commented
closing this PR as there were no changes made after providing the comments from 7 Oct 2018. If you get time to rework on the comments you can open the PR for review.

2020-04-07 06:20 UTC, closed without merging