fmt(cstyle): cstyle fixes in src/assert.h
openebs/istgt pull request #114
Opened 2018-10-06 15:17 UTC by avnish98

Removed "preprocessor statement not in column 1" error

2018-10-07 21:37 UTC, payes approved these changes

2018-10-08 05:58 UTC, vishnuitta commented on src/assert.h
> -	    #A, #B)))
can you please make this as:
```
 	    REPLICA_ERRLOG("(" %s ") implies (" %s ")", #A, #B)))

2018-10-08 05:59 UTC, vishnuitta requested changes
changes requested as provided in comments

2018-10-08 14:01 UTC, avnish98 commented
@vishnuitta I have done the changes you requested

2018-10-08 15:58 UTC, vishnuitta approved these changes
changes are good

2018-10-09 05:59 UTC, merged