Updated header files with fixes to cstyle errors
openebs/istgt pull request #117
Opened 2018-10-07 00:30 UTC by michizhou

Closes openebs/openebs#2036.

Signed-off-by: Michael Zhou <myz227@nyu.edu>

2018-10-08 04:33 UTC, utkarshmani1997 approved these changes
LGTM

2018-10-08 06:50 UTC, vishnuitta requested changes
all errors are not fixed. Below is cstyle output on latest files:
```
./cstyle.pl src/istgt_scsi.h 
src/istgt_scsi.h: 29: #define followed by space instead of tab

./cstyle.pl src/istgt_sock.h 
src/istgt_sock.h: 29: #define followed by space instead of tab
src/istgt_sock.h: 35: indent by spaces instead of tabs
src/istgt_sock.h: 46: indent by spaces instead of tabs
```

2018-10-08 06:51 UTC, vishnuitta commented on src/istgt_sock.h
> -int istgt_getaddr(int sock, char *saddr, int slen, char *caddr, int clen, uint32_t *iaddr, uint16_t *iport);
code changes can be like this:
```
--- a/src/istgt_sock.h
+++ b/src/istgt_sock.h
@@ -26,13 +26,13 @@
  */
 
 #ifndef ISTGT_SOCK_H
-#define ISTGT_SOCK_H
+#define        ISTGT_SOCK_H
 
 #include <stddef.h>
 #include <unistd.h>
 
 int istgt_getaddr(int sock, char *saddr, int slen, char *caddr, int clen,
-                  uint32_t *iaddr, uint16_t *iport);
+    uint32_t *iaddr, uint16_t *iport);
 int istgt_listen(const char *ip, int port, int que);
 int istgt_listen_unx(const char *lpath, int que);
 int istgt_connect(const char *host, int port);
@@ -43,7 +43,7 @@ int istgt_set_recvlowat(int s, int nbytes);
 ssize_t istgt_read_socket(int s, void *buf, size_t nbytes, int timeout);
 ssize_t istgt_write_socket(int s, const void *buf, size_t nbytes, int timeout);
 ssize_t istgt_readline_socket(int sock, char *buf, size_t size, char *tmp,
-                        size_t tmpsize, int *tmpidx, int *tmpcnt, int timeout);
+    size_t tmpsize, int *tmpidx, int *tmpcnt, int timeout);
 ssize_t istgt_writeline_socket(int sock, const char *buf, int timeout);
 
 #endif /* ISTGT_SOCK_H */

```

2018-10-08 21:38 UTC, michizhou commented
Hi @vishnuitta, I have incorporated the changes you requested as per your review. Let me know if any other changes are needed. Thanks!

2018-10-09 03:51 UTC, vishnuitta requested changes
changes are good. There seems to be an extra file .DS_Store. Can you please remove that?

2018-10-09 05:23 UTC, michizhou commented
@vishnuitta I just removed the extra .DS_Store file like you asked.

2018-10-09 06:01 UTC, vishnuitta approved these changes
changes are good

2018-10-09 07:24 UTC, merged