Fix cstyle error in ./src/istgt_cmd_table.c #2056
openebs/istgt pull request #125
Opened 2018-10-07 16:53 UTC by krishnakarthik1309

Fixed `./src/istgt_cmd_table.c` as mentioned in issue [here](https://github.com/openebs/openebs/issues/2056)

2018-10-09 12:29 UTC, payes requested changes
@krishnakarthik1309 make is failing, please rectify the errors, and update the PR.

2018-10-09 16:55 UTC, krishnakarthik1309 commented
@payes fixed make file. Can i know output of Better Code Hub, to fix that.

2020-04-10 00:27 UTC, payes approved these changes

2020-05-05 15:01 UTC, mynktl commented
Closing this PR due to inactivity. @krishnakarthik9 Feel free to reach out us.

2020-05-05 15:01 UTC, closed without merging