[#2054] Fix cstyle error in ./src/istgt_crc32c.c
openebs/istgt pull request #128
Opened 2018-10-07 20:02 UTC by nfayazov

Signed off by: Nadir Fayazov nfayazov@gmail.com

**What this PR does / why we need it:**
Fix cstyle error in ./src/istgt_crc32c.c

2018-10-08 05:05 UTC, utkarshmani1997 commented on src/istgt_crc32c.c
> +static uint32_t istgt_crc32c_xor			 = ISTGT_CRC32C_XOR;
@nfayazov fix indentation here

2018-10-08 05:06 UTC, utkarshmani1997 requested changes
@nfayazov changes look good to me. Have given comment to fix indentation.

2018-10-08 10:40 UTC, agarwal-akash commented
@utkarshmani1997 PR to this issue has already been submitted yesterday [#2054](https://github.com/openebs/istgt/pull/123)

2018-10-11 20:48 UTC, nfayazov commented
The other PR is closed, I will fix the indentation.

2018-10-11 21:34 UTC, nfayazov commented
@utkarshmani1997 I think it looks better now.

2018-10-26 05:30 UTC, vishnuitta approved these changes
changes are good

2018-10-26 06:22 UTC, merged