Cstyle linting for istg lu.c
openebs/istgt pull request #142
Opened 2018-10-12 06:13 UTC by diegous

This file is very large and had many things to fix, so I grouped each type of fix in a different commit. 

I haven't yet fixed "line > 80 characters" because I thought that it would make this PR too big.

Please, let me know what you guys think.

2018-10-13 04:49 UTC, utkarshmani1997 requested changes
@diegous thanks for the fixes, this look good to me. Have provided the comments regarding multiline comments. Correct me if i'm wrong.

2018-10-13 04:49 UTC, utkarshmani1997 commented on src/istgt_lu.c
> +			return (0ULL); // Shuld this be NULL?
it's used as `unsigned long long zero` . kindly remove the comment

2018-10-13 04:49 UTC, utkarshmani1997 commented on src/istgt_lu.c
> +	// MTX_UNLOCK(&lu->istgt->mutex);
shouldn't multiline comments be in `/*        */` this form ?

2018-10-13 04:49 UTC, utkarshmani1997 commented on src/istgt_lu.c
same comment as earlier

2018-10-13 04:49 UTC, utkarshmani1997 commented on src/istgt_lu.c
>  						MTX_UNLOCK(&lu->mutex);
same comment as earlier

2018-10-13 04:49 UTC, utkarshmani1997 commented on src/istgt_lu.c
> +	// }
same comment as earlier

2018-10-13 18:10 UTC, diegous commented on src/istgt_lu.c
> +	alloc_len += ISCSI_ALIGN(sizeof *lu_task->lu_cmd.pdu); // I'm not sure if this is 'sizeof (*lu_task)->lu_cmd.pdu' or 'sizeof (*lu_task->lu_cmd.pdu)'
I wasn't sure how to solve this

2018-10-26 08:27 UTC, vishnuitta commented on src/istgt_lu.c
> +	alloc_len += ISCSI_ALIGN(sizeof *lu_task->lu_cmd.pdu); // I'm not sure if this is 'sizeof (*lu_task)->lu_cmd.pdu' or 'sizeof (*lu_task->lu_cmd.pdu)'
you can make it as sizeof (struct iscsi_pdu_t)

2018-10-26 08:51 UTC, vishnuitta approved these changes
changes are good.
Other cstyle error 'line > 80 characters' can be done in a different PR

2018-10-26 22:40 UTC, diegous commented
@utkarshmani1997 I've corrected the last of the comments, and fixed a couple of lines added when the 'replication' branch was updated. If everything looks good enough to merge we should probably squash all the commits before.

2018-10-27 09:53 UTC, merged