[TA3457] feat(istgtcontrol): Add uptime
openebs/istgt pull request #85
Opened 2018-10-04 12:42 UTC by utkarshmani1997

Signed-off-by: Utkarsh Mani Tripathi <utkarshmani1997@gmail.com>

2018-10-18 20:00 UTC, vishnuitta commented on src/istgt_iscsi.c
> +						spec->totalwritetime += (_r.tv_sec * 1000000000) + (_r.tv_nsec);
`_r` is calculated from cmd's `times` array. Don't depend on times array

2018-10-18 20:06 UTC, vishnuitta reviewed
time taken to serve an IO shouldn't depend on 'times' data structure. Other changes are fine.

2018-10-22 05:54 UTC, utkarshmani1997 commented on src/istgt_iscsi.c
> +						spec->totalwritetime += (_r.tv_sec * 1000000000) + (_r.tv_nsec);
ok

2018-10-23 03:00 UTC, mynktl requested changes

2018-10-23 03:00 UTC, mynktl commented on src/istgt_iscsi.c
> +						diff = (now.tv_sec - start_rw_time.tv_sec)*1000000000 + (now.tv_nsec - start_rw_time.tv_nsec);
Better to use MACRO like NANOSEC  instead of a number.
What if `start_rw_time.tv_nsec` is greater than `now.tv_nsec`?
Use `timesdiff` MACRO from `istgt_misc.h`.

2018-10-23 03:00 UTC, mynktl commented on src/istgt_iscsi.c
> +						#endif
you are setting the start time for every IO in `istgt_iscsi_read_pdu` and calculating time from `prof_log` which will be called from `sender thread`. This will not give correct information about read/write time.
Better to use an array or new variable in `lu_cmd` to track time per IO.

2018-10-25 07:07 UTC, mynktl approved these changes

2018-10-25 12:41 UTC, vishnuitta approved these changes
changes are good

2018-10-25 13:01 UTC, merged